# Setup
```{r}
library(data.table)

if (!require('picsure', quiet=T)) {
  Sys.setenv(TAR = '/bin/tar')
  options(unzip = 'internal')
  remotes::install_github(
    repo = 'hms-dbmi/pic-sure-r-adapter-hpds',
    ref  = 'main', force=T
  )
}
```
```{r}
picsure_url = 'https://picsure.biodatacatalyst.nhlbi.nih.gov/picsure'
token <- scan('picsure_token.txt', what='character', quiet=T)
session <- picsure::bdc.initializeSession(picsure_url, token) |> picsure::bdc.setResource('AUTH')
```

# Search variables
## Get search objects
This is analogous to exploring variables in the PIC-SURE web UI.
```{r}
# For some reason, query wait time scales with `limit`, so set as low as possible while still getting all variables.
t0 <- Sys.time()
mesa_ids_search <- picsure::bdc.searchPicsure(session, 'phs001416',               limit=  200) |> setDT()
    mesa_search <- picsure::bdc.searchPicsure(session, 'phs000209',               limit=25000) |> setDT()
     fhs_search <- picsure::bdc.searchPicsure(session, 'phs000974',               limit= 2000) |> setDT()
  topmed_search <- picsure::bdc.searchPicsure(session, 'DCC Harmonized data set', limit=  500) |> setDT()
Sys.time() - t0

combined_search <- rbindlist(list(mesa_search, fhs_search))
rm(combined_search)
```

## Narrow down desired variables
### TOPMed harmonized variables
```{r}
#colnames(fread('data/raw/phenotypes/MESA_HDL_PA_covars_12345.csv')) |> {\(nm) sub('.*\\\\(.*)\\\\$', '\\1', nm)}()
tmp <- topmed_search[,-'name'][, var_description := gsub('\n',' ',var_description)] # For manual viewing

topmed_vars <- topmed_search[
  ][1:.N
  ][, -'values'
  ][grepl(x = tolower(paste(var_id, var_name, var_description)), pat = paste(collapse='|', c(
      'lipid_lowering_medication',
      'fasting_lipids', #(This is an indicator var of whether they fasted >=8hr b4 lipid measures or not)
      'hdl',
      'triglycerides',
      'bmi_baseline', # 'Body mass index calculated at baseline.'
      'ever_smoker_baseline',
      'current_smoker_baseline',
      'sleep_duration',
      'race_us',
      'subcohort', # 'A distinct subgroup within a study, generally indicating subjects who share similar characteristics due to study design. Subjects may belong to only one subcohort.'
      'hispanic_or_latino',
      'geographic_site',
      'annotated_sex',
      'age_at_hdl', 'age_at_triglycerides', 'age_at_ever_smoker', 'age_at_current_smoker', 'age_at_fasting_lipids', 'age_at_lipid_lowering', 'age_at_sleep'
    )))
]
```


### FHS search
```{r}
tmp <- fhs_search[,-'name'][, var_description := gsub('\n',' ',var_description)] # For manual viewing

fhs_vars <- fhs_search[
  ][grepl(paste(collapse='|', c(
      'Age_at_collection', # Which one?
      'AGE_OF_COLLECTION',
      'Batch',
      'Collection_visit', # Which one?
      'extractDate',
      'IS_TUMOR', # all are "no"
      'SEX',
      'SAMPLE_ID',
      'PlateId', 'Sample_well_ID', 'Sample_container_ID',
      'SUBJECT_ID'
    )), var_name)
]
```

### MESA search
```{r}
tmp <- mesa_search[,-'name'][, var_description := gsub('\n',' ',var_description)] # For manual viewing

mesa_vars <- mesa_search[
  ][grepl(paste(collapse='|', c(
      'MESA_Exam[0-9]Main',
      'MESA_AncilMesaMineralMetabolite',        # nac
      'MESA_AncilMesaNeighborScalesExam',       # ahei_2010
      'MESA_AncilMesaNeighborScalesSodiumExam', # dash_sodium
      'MESA_exam[0-9]dietnutrients',            # nan
      'MESA_AncilMesaNeighborSESExam'           # F1_PC2
    )), group_name)
  ][grepl(paste(collapse='|', c(
      'sidno',
      '^age[0-9]c$',
      'ahei',
      'alc',
      'bmi[0-9]c',
      'cig[0-9]c',
      'dash_sodium',
      'F1_PC2',
      'gender',
      'glucos[0-9]c',
      'hba',
      'hdl[0-9]$',
      'income',
      'ins[0-9]c',
      'lipid',
      'month',
      'nac',
      'nan[0-9]c',
      'race1c',
      'season',
      'site[0-9]c',
      'exercm[0-9]c', 'pamcm[0-9]c', 'pavcm[0-9]c', 'pamvcm[0-9]c'
    )), var_name)
  #][, unique(group_name)
  #][grep('sidno', var_name)
]
```
```{r}
tmp <- mesa_ids_search[,-'name']

mesa_id_vars <- mesa_ids_search[
  ][grepl(paste(collapse='|', c(
      'TOPMed_MESA_Sample',
      'TOPMed_MESA_Subject',
      'TOPMed_MESA_Metabolomics'
    )), group_name)
  #][, -'values'
]
```


# Actually getting data with a Query
```{r}
do_query <- \(varnames) bdc.newQuery(session) |> addClause(keys=varnames, type='ANYOF') |> runQuery(resultType='DATA_FRAME') |> setDT()

mesa_query    <- do_query(   mesa_vars$name)
mesa_id_query <- do_query(mesa_id_vars$name)
fhs_query     <- do_query(    fhs_vars$name)
topmed_query  <- do_query( topmed_vars$name)
```

```{r}
fwrite(mesa_query, 'mesa_picsure_variables.csv')
fwrite(mesa_id_query, 'mesa_id_picsure_variables.csv')
fwrite(fhs_query, 'fhs_picsure_variables.csv')
fwrite(topmed_query, 'topmed_picsure_variables.csv')
```
