NOTE: this does not work out of the box. Mummichog is a bit annoying to run. The latest update introduced a bug so you have to use version 2.6.1. It also only works on Python 3.8.\
If you have `pyenv` you can do `pyenv install 3.8 && pyenv global 3.8 && pip install mummichog==2.6.1`.

# Mummichog
```{r setup}
library(data.table)
dir.create('scratch/mummichog_input', recursive=T)
dir.create('scratch/mummichog_output',recursive=T)
```

```{r data}
tmp[snp=='chr14_88305056_G_A' & single_exam==F & model=='hdl~met*snp']
tmp <- fread('runs.csv')
tmp2 <- fread('data/derived/metabolomics/met_info.csv') 
fread('data/derived/metabolomics/met_info-mesa.csv')[
  ][, .(unique_met_id,MZ,RT)
  ][fread('runs.csv')[
      ][snp=='chr14_88305056_G_A' & single_exam==F & model=='hdl~met*snp'
      #][single_exam==F & model=='met~hdl'
      ][, .(met, p, t)
    ], on=.(unique_met_id=met)
  ][!is.na(MZ) & !is.na(RT)
    , .(MZ,RT,p,t,unique_met_id) |> fwrite(paste0('scratch/mummichog_input/mummichog_input-chr14_variant-v2.tsv'), sep='\t')
]
```

```{r mummichog}
fs <- list.files('scratch/mummichog_input/',full.names=T)
fs <- 'scratch/mummichog_input/mummichog_input-chr14_variant-v2.tsv'
t0 <- Sys.time()
lapply(fs, \(f) {
  print(f)
  system(paste('mummichog -f', f, '-o', basename(f)))

  # Hacky stuff to move mummichog's strangely-named outputs to where I want
  out_dirnm <- sub('mummichog_input-','',sub('.csv$','',basename(f)))
  out_dirnm2 <- paste0('scratch/mummichog_output/',out_dirnm)
  unlink(out_dirnm2,recursive=T)
  file.rename(list.files(pattern=out_dirnm), out_dirnm2)
})
Sys.time()-t0
```
