```{r}
library(data.table)
library(parallel)
options(mc.cores=6L)
dir.create('scratch/mummichog_input', recursive=T)
dir.create('scratch/mummichog_output',recursive=T)
```

```{r}
tmp <- fread('mwas.csv')
tmp2 <- fread('metabolomics/met_info.csv') 
fread('metabolomics/met_info.csv')[
  ][, .(unique_met_id,MZ,RT)
  ][fread('mwas.csv')[
      ][, .(unique_met_id,
            p=intrx_lmm_p_chr14_88305056_G_A,
            z=intrx_lmm_est_chr14_88305056_G_A/intrx_lmm_se_chr14_88305056_G_A
    )], on='unique_met_id', allow.cartesian=T
  ][!is.na(MZ) & !is.na(RT)
  ][, .(MZ,RT,p,z) |> fwrite(paste0('scratch/mummichog_input/mummichog_input-chr14_variant.tsv'), sep='\t')
   #, by=variant # TODO can make this more generalizable once I restructure the `mwas` object to have `LMM or LM` and `variant` columns. 
]
```

```{r}
fs <- list.files('scratch/mummichog_input/',full.names=T)
t0 <- Sys.time()
mclapply(fs, \(f) {
  print(f)
  system(paste('mummichog -f', f, '-o', basename(f)))

  # Hacky stuff to move mummichog's strangely-named outputs to where I want
  out_dirnm <- sub('mummichog_input-','',sub('.csv$','',basename(f)))
  out_dirnm2 <- paste0('scratch/mummichog_output/',out_dirnm)
  unlink(out_dirnm2,recursive=T)
  file.rename(list.files(pattern=out_dirnm), out_dirnm2)
})
writeLines(capture.output(Sys.time()-t0), 'howlong.txt')
```
